<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
	<div class="col-md-12">
		<h1>Posts - <small>Gerencie suas postagens</small>
            <a href="#" class="btn btn-warning pull-right" data-toggle="modal" data-target="#myModal">Inserção Via Modal</a>
            <a href="<?=HOME . '/posts/new';?>" class="btn btn-success pull-right">Criar Novo Post</a>
        </h1>
		<hr>
	</div>

    <div class="col-md-12">
	    <?php require VIEWS_PATH . 'includes/messages.phtml';?>
    </div>

	<div class="col-md-12">
		<table class="table">
			<thead>
			<tr>
				<th>#</th>
				<th>Titulo</th>
				<th>Criado em</th>
				<th></th>
			</tr>
			</thead>
			<tbody>
			<?php foreach($this->posts as $p):?>
			<tr>
				<td><?=$p['id'];?></td>
				<td><?=$p['title'];?></td>
				<td><?=date('d/m/Y H:i:s', strtotime($p['created_at']));?></td>
				<td>
					<a href="<?=HOME;?>/posts/edit/<?=$p['id'];?>" class="btn btn-default">
						Editar
					</a>
					<a href="<?=HOME;?>/posts/remove/<?=$p['id'];?>" class="btn btn-danger">
						Excluir
					</a>
				</td>
			</tr>
			<?php endforeach;?>
			</tbody>
		</table>
	</div>

</div>


<div class="modal fade" tabindex="-1" role="dialog" id="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <form action="" class="formData" method="post">
                    <div class="form-group">
                        <label>Titulo</label>
                        <input type="text" class="form-control" name="title">
                    </div>


                    <div class="form-group">
                        <label>Descrição</label>
                        <input type="text" class="form-control" name="description">
                    </div>

                    <button type="submit" class="btn btn-success">Enviar</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
