<?php require VIEWS_PATH . '/admin/includes/header.phtml';?>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2>Editar Produto</h2>
				<hr>
			</div>
		</div>

		<div class="col-md-12">
			<?php require VIEWS_PATH . 'includes/messages.phtml';?>
		</div>

		<div class="row">
			<form action="<?=HOME;?>/admin/products/edit/<?=$this->product['id'];?>" method="post" enctype="multipart/form-data">
				<div class="col-md-12">
					<div class="form-group">
						<label>Nome do produto</label>
						<input type="text" class="form-control" name="name" value="<?=$this->product['name'];?>">
					</div>
				</div>

				<div class="col-md-12">
					<div class="form-group">
						<label>Descrição</label>
						<input type="text" class="form-control" name="description" value="<?=$this->product['description'];?>">
					</div>
				</div>

				<div class="col-md-12">
					<div class="form-group">
						<label>Conteúdo</label>
						<textarea name="content" class="form-control"><?=$this->product['content'];?></textarea>
					</div>
				</div>

				<div class="col-md-12">

					<div class="row">

						<div class="col-md-6">
							<div class="form-group">
								<label>Preço</label>
								<input type="text" class="form-control" name="price"
								       value="<?=number_format($this->product['price'], 2, ',', '.');?>">
							</div>
						</div>

						<div class="col-md-6">
							<label>Status produto</label>
							<select name="is_active" class="form-control">
								<option value="1" <?php if($this->product['is_active']):?> selected <?php endif;?>>Ativo</option>
								<option value="0" <?php if(!$this->product['is_active']):?> selected <?php endif;?>>Inativo</option>
							</select>
						</div>

					</div>
				</div>


                <div class="col-md-12">
                    <div class="form-group">
                        <label>Selecione as imagens do produto</label>
                        <input type="file" name="images[]" multiple class="form-control">
                    </div>
                </div>


                <div class="col-md-12">
					<button type="submit" class="btn btn-lg btn-success">Atualizar Produto</button>
				</div>
			</form>
		</div><!-- Fechamento da row dos inputs -->
        <div class="row">
            <div class="col-md-12">
                <h2>Imagens do Produto</h2>
                <hr>
            </div>
        </div>
        <div class="row">
            <?php foreach($this->product['images'] as $image): ?>
            <div class="col-md-3">
                <img src="<?=HOME;?>/uploads/products/<?=$image['image'];?>"
                     alt="Image do produto <?=$this->product['name'];?>"
                     class="img-responsive">
            </div>
            <?php endforeach; ?>
        </div>
	</div>
<?php require VIEWS_PATH . '/admin/includes/footer.phtml';?>